server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024 # Compress the response only if the response size is at least 1KB
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://ep-broad-block-a4snyxgf-pooler.us-east-1.aws.neon.tech:5432/neondb
    username: neondb_owner
    password: npg_pOeTmjZXb51H
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    messages:
      basename: messages
      encoding: UTF-8
      fallback-to-system-locale: false
      use-code-as-default-message: true


app:
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080
    allowed-methods: GET, POST, PUT, DELETE, OPTIONS
    allowed-headers: "*"
    exposed-headers: "*"
    allow-credentials: true
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
    tokenRefreshExpirationMsec: 864000000
  slack:
    webhookUrl: https://hooks.slack.com/services/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
#logging:
#  level:
#    org.springframework.security: DEBUG


